### PR TITLE
adding com_rpost_rmail zimlet

### PR DESCRIPTION
**Pull request by ghost**
Adding Zimlet as requested by jennifer.goodwin

### CODE REVIEW

**Comment by ghost** [comment]
@kalpeshhpatel could you take care of it from here, if there are any questions, let me know.

**Comment by kalpeshhpatel** [comment]
@barrydegraaff , can you please explain bit more about what you are expecting from me here?

Thanks

**Comment by ghost** [comment]
I will wait for the correct person in Zimbra to pick this up, please do not merge this one yet, as a newer version is here: https://github.com/Zimbra-Community/rmail

**Comment by jeastman** [comment]
We have been discussing this internally to understand the correct course of action here. My feeling is that we should just source this from your repository and NOT pull the code into the project itself. This would provide a much better longer-term solution, I believe.

**Comment by ghost** [comment]
Hello John,

Yeah sounds good to me, closing the PR.

**Pull request closed without merging**
